name: Process sync signal for messenger $$$NAME

on:
  repository_dispatch:
    types: $$$SENDER_EVENTS

env:
  HUSKY: 0

jobs:
  $$$NAME-messenger-receive:
    runs-on: ubuntu-latest
    outputs:
      sender_event: ${{ github.event.action }}
      has_changes: ${{ steps.check-changes.outputs.has_changes }}
    steps:
      - name: Create temp dirs
        run: mkdir data-src data-dist
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.event.client_payload.source }}
          ref: ${{ github.event.client_payload.ref }}
          path: data-src
      - uses: actions/checkout@v3
        with:
          path: data-dist
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14.15.3
      - run: |
          cd data-dist
          npm i
          npm run receive ../data-src
      - name: Check for changes
        id: check-changes
        run: |
          cd data-dist
          if [ -n "$(git status --porcelain $$$DIR_NAME/)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Upload changed files
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: changed-data
          path: data-dist/$$$DIR_NAME
  commit-changes:
    needs: $$$NAME-messenger-receive
    runs-on: ubuntu-latest
    env:
      SENDER_EVENT: ${{ needs.$$$NAME-messenger-receive.outputs.sender_event }}
    if: needs.$$$NAME-messenger-receive.outputs.has_changes == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Download changed files
        uses: actions/download-artifact@v4
        with:
          name: changed-data
          path: data
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: receive data from \`${SENDER_EVENT}\`"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
